name: christmas-season
main: de.boondocksulfur.christmas.ChristmasSeason
version: 2.1.0
api-version: '1.21'
folia-supported: true
author: BoondockSulfur
commands:
  xmas:
    description: Schaltet das Weihnachts-Event ein/aus
    usage: /xmas <on|off|status|reload|biome|storm>
    permission: xmas.admin
  xmasgift:
    description: Spawnt ein Geschenk an deiner Position
    usage: /xmasgift
    permission: xmas.admin
permissions:
  xmas.admin:
    default: op
